### ISSUE TITLE
no lock on my page

### ISSUE THREAD

**Issue by saksiva** [fac-15/santas_secret#24]
![image](https://user-images.githubusercontent.com/41472850/50338523-75772600-050c-11e9-8119-7756b7f2297a.png)

**Comment by charlielafosse** [comment]
Same ;--(

**Comment by Oliversw** [comment]
#LinuxLife

**Comment by charlielafosse** [comment]
![](https://cdn.drawception.com/images/panels/2015/3-11/B7t2XjmSfO-10.png)

**Comment by Oliversw** [comment]
Get a mac

**Comment by Oliversw** [comment]
KIDDING

**Comment by Oliversw** [comment]
(kind of)
